# Site settings
title: bochinche's blog
#email: justshiat@gmail.com
description: >-
  bochinche is the Venezuelan word for a social gathering, particularly a lively one.
  This blog is in Spanish, English and German. The posts are related to current topics I am working on.
domain: "bochinche.github.io"
baseurl: ""                                # the subpath of your site, e.g. /blog
url: "https://bochinche.github.io"         # the base hostname & protocol for your site
github_username: bochinche

# Build settings
theme: minima

# If you later want a dark skin, you can uncomment and adjust this block:
# minima:
#   skin: dark

plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages: 
 - index.md
 - social-games.md


  # jekyll-seo-tag is already pulled in by github-pages, no need to list explicitly

# Exclude from processing (optional â€“ keep commented unless you really want to change it)
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

